### ISSUE TITLE
Is sorted

### ISSUE THREAD

**Issue by weissfennek** [weissfennek/ScriptsDump#106]
Use TDD to implement a function that takes a list of integers as input and returns True if the input list is sorted in ascending order, and False otherwise. The function should correctly identifie sorted lists, regardless of the input's length or content.

**Comment by abdelfattehjarray** [comment]
GGTeam took this TDD project

**Comment by abdelfattehjarray** [comment]
repository link : https://github.com/abdelfattehjarray/TDDproject-is_ascending.git

**Comment by abdelfattehjarray** [comment]
![image](https://user-images.githubusercontent.com/125979681/233755361-1d70feec-6fd0-4d8a-87b4-55df56661d57.png)
