### ISSUE TITLE
Filter short strings

### ISSUE THREAD

**Issue by weissfennek** [weissfennek/ScriptsDump#107]
Use TDD to write a function that takes a list of strings as input and returns a new list containing only the strings that are longer than a specified length. The function should correctly filter out the strings that are too short, regardless of the length of the input list or the specified length.

**Comment by aboubacar-said** [comment]
Salam Madame le groupe aboubacar-said et Dande-ronelbaye va travailler sur #107

**Comment by aboubacar-said** [comment]
Notre depôt a besoin d'être revu
[https://github.com/aboubacar-said/projet-1.git](https://github.com/aboubacar-said/projet-1.git)

**Comment by weissfennek** [comment]
The following needs to be done:
- add a screenshot of the results of your tests
- close the issue
- create a new issue to ask for reviewing your repository
