### ISSUE TITLE
RTT: linear_search_recursion.py

### ISSUE THREAD

**Issue by G-Jasser** [weissfennek/ScriptsDump#43]
Request to test the script: <code>linear_search_recursion.py</code>.

Path: <a href="https://github.com/weissfennek/ScriptsDump/blob/master/Arrays-searching/src/linear_search_recursion.py">Arrays-searching/src/linear_search_recursion.py</a>.

**Comment by weissfennek** [comment]
Looks good. 
Please leave this issue open until you finish writing the tests.

**Comment by G-Jasser** [comment]
@weissfennek We have finished writing testing for the script (covering only all instructions). What is the next task?

**Comment by weissfennek** [comment]
The next task is in Homework5
