### ISSUE TITLE
Request to test : linear_search.py

### ISSUE THREAD

**Issue by AssemAloui** [weissfennek/ScriptsDump#44]
Request to test the script: linear_search.py
<a href="https://github.com/weissfennek/ScriptsDump/blob/master/Arrays-searching/src/linear_search/linear_search.py">Arrays-searching/src/linear_search/linear_search.py</a>

**Comment by weissfennek** [comment]
OK.
Please leave this issue open until you finish testing the script.

**Comment by weissfennek** [comment]
Regarding your question about calling a method from another file, it is possible to import a method from a file and use it. For example importing the print_result method can be done with the following line:
from linear_search import print_result 
If you have further questions feel free to ask them in the Discussions
