### ISSUE TITLE
Request to test the script: Rat_In_A_Maze.java

### ISSUE THREAD

**Issue by Hassenbd** [weissfennek/ScriptsDump#46]
Backtracking/Rat_In_A_Maze/Rat_In_A_Maze.java

**Comment by weissfennek** [comment]
Ok. Since the code is written in Java, you would need to use JUnit instead of pytest.
Leave this issue open until you finish testing.
Close issue #45 as a duplicate of this one.

**Comment by weissfennek** [comment]
Also assign this issue to yourself
