### ISSUE TITLE
Test de BinarySearch 

### ISSUE THREAD

**Issue by SarraAmorri** [weissfennek/ScriptsDump#47]
je veux testé c'est code [ScriptsDump](https://github.com/weissfennek/ScriptsDump)/[Arrays-searching]

**Comment by weissfennek** [comment]
There are many scripts in Arrays-searching. Which one would you like to test?

**Comment by SarraAmorri** [comment]
je veux testé c'est code [ScriptsDump](https://github.com/weissfennek/ScriptsDump)/[Arrays-searching](https://github.com/weissfennek/ScriptsDump/tree/master/Arrays-searching)/[src]

**Comment by SarraAmorri** [comment]
je veux testé c'est code  [ScriptsDump](https://github.com/weissfennek/ScriptsDump)/[Arrays-searching](https://github.com/weissfennek/ScriptsDump/tree/master/Arrays-searching)/[src](https://github.com/weissfennek/ScriptsDump/tree/master/Arrays-searching/src)/[binary_search](https://github.com/weissfennek/ScriptsDump/tree/master/Arrays-searching/src/binary_search)/BinarySearch.java /

**Comment by weissfennek** [comment]
If you test BinarySearch.java you will need to use JUnit. I recommend you to test binarySerach.py instead, then you can use pytest.
Please assign the issue to yourself and leave the issue open until you finish testing
