### ISSUE TITLE
Test insert_sort.py

### ISSUE THREAD

**Issue by aboubacar-said** [weissfennek/ScriptsDump#61]
Nom du fichier : Insertion_Sort.py
Emplacement :https://github.com/weissfennek/ScriptsDump/blob/master/Arrays-Sorting/src/Insertion_Sort/Insertion_Sort.py

**Comment by weissfennek** [comment]
Ok
Please assign the issue to yourself

**Comment by aboubacar-said** [comment]
Salut Madame En ce qui concerne l'assignement de l'issue suis-je contraint d'ajouter ainsi tous les membres du groupe comme On l'a fait lors de la creation de ce dernier ou en tant qu'administrateur de l'equipe ma voie suffira l'autre Merci de me repondre.
