### ISSUE TITLE
Highest and lowest numbers in a list 

### ISSUE THREAD

**Issue by weissfennek** [weissfennek/ScriptsDump#94]
Use TDD to implement a function that takes a list of integers as input and returns the highest and lowest numbers in the list. The function should handle various inputs, including lists with different sizes and different sets of numbers.

**Comment by IslemBaaroun** [comment]
The link of our repository : 
 https://github.com/IslemBaaroun/Homework6.git

**Comment by IslemBaaroun** [comment]
![screenshot tests](https://user-images.githubusercontent.com/123880545/232250870-c3e67501-37f2-44b8-a8f6-359178a736c9.png)

**Comment by IslemBaaroun** [comment]
screenshot.png

**Comment by IslemBaaroun** [comment]
![screenshot](https://user-images.githubusercontent.com/123880545/232326709-7f62869e-7944-42ae-97aa-176bd7adb437.png)
