### ISSUE TITLE
Number of words in a string

### ISSUE THREAD

**Issue by weissfennek** [weissfennek/ScriptsDump#95]
Use TDD to write a function that takes a string as input and returns the number of words in the string. The function should correctly handle various types of inputs, such as empty strings, strings with no spaces, and strings with leading or trailing spaces.

**Comment by samarbh** [comment]
https://github.com/samarbh/NumberOfWords.git

**Comment by samarbh** [comment]
![Capture d’écran 2023-04-27 204543](https://user-images.githubusercontent.com/126614871/234975931-a048eaa2-dd7a-4ace-ae16-9de17eabea6d.png)

**Comment by samarbh** [comment]
![image_2023-04-27_205558029](https://user-images.githubusercontent.com/126614871/234976625-956a3fc7-8c6d-4f61-8fb5-95df0166df3e.png)
