### ISSUE TITLE
Find common elements in two lists

### ISSUE THREAD

**Issue by weissfennek** [weissfennek/ScriptsDump#96]
Use TDD to implement a function that takes two lists of integers as input and returns a new list containing the elements that are common to both input lists. The function should handle various inputs, including lists with different sizes and different sets of numbers.

**Comment by G-Jasser** [comment]
https://github.com/G-Jasser/Distracded

**Comment by G-Jasser** [comment]
![pytest](https://user-images.githubusercontent.com/123377848/229380935-404d59f7-cb42-4d09-b33f-3ae8a30e0fc3.png)
![mocktests](https://user-images.githubusercontent.com/123377848/229380952-d87526f5-62ec-4e6b-a86f-81e88bb00439.png)
