### ISSUE TITLE
Swap key and value in dictionary

### ISSUE THREAD

**Issue by weissfennek** [weissfennek/ScriptsDump#97]
Use TDD to implement a function that takes a dictionary as input and returns a new dictionary with the keys and values swapped. The function should handle various inputs, including dictionaries with different sizes and different sets of keys and values

**Comment by Mahamat-Brahim-Abderassoul** [comment]
https://github.com/Mahamat-Brahim-Abderassoul/LGLSI2_DYNAMIQUE

**Comment by Mahamat-Brahim-Abderassoul** [comment]
hello / good evening depending on the arrival of the message.
we couldn't finish our test, we hope to finish it soon

**Comment by Kineba** [comment]
![Uploading image_2023-05-03_201634317.png…]()
