### ISSUE TITLE
Remove vowels

### ISSUE THREAD

**Issue by weissfennek** [weissfennek/ScriptsDump#98]
Use TDD to implement a function that takes a string as input and returns the string with all vowels removed. The function should correctly remove all vowels from the input string, regardless of the input's length or content.

**Comment by Oussama-Mrabet** [comment]
https://github.com/Oussama-Mrabet/remove-vowels-test

**Comment by Oussama-Mrabet** [comment]
![test_screenshot.jpg](https://user-images.githubusercontent.com/63909492/229367860-4224dcd9-99c5-495f-a820-a2e682cbc60a.jpg)
